### ISSUE TITLE
[NOT AN ISSUE] Playing not just one music

### ISSUE THREAD

**Issue by Aqua-22** [markondej/fm_transmitter#122]
Hello i am wondering if i can have a folder in the fm_transmitter folder whit a lot of music and have them play after the other.

**Comment by superamario64** [comment]
Did you ever figure out how to do this?

**Comment by Markieyer** [comment]
You can use a wildcard to do all music, so instead of putting "/home/Music/My\ Song.wav", you'd put "/home/Music/*.wav"
It'll do it all in alphabetical order, keep that in mind, I've yet to find a way to do a truly random or, 'shuffle' with it yet, but still, best way of playing all your music is like that

**Comment by superamario64** [comment]
oh great! thanks a lot
one way you could shuffle the songs is to maybe write a simple script that renames all the files to `001.wav`, `002.wav` in a random way
