### ISSUE TITLE
Changing pin

### ISSUE THREAD

**Issue by DrayNeur** [markondej/fm_transmitter#125]
I'd like to create a portable version of my raspberry but i need a small screen, the problem is that every screen use some pins including the pin that use fm transmitter. Any help ?

**Comment by markondej** [comment]
See RPi peripherals documentation, c. 6.2. 
https://www.raspberrypi.org/documentation/hardware/raspberrypi/bcm2835/BCM2835-ARM-Peripherals.pdf
Each output marked as GPCLK may be used in theory. Currently only GPIO4 and GPIO21 are supported by this project. In order to switch to GPIO21 please see instructions for Raspberry Pi 4, as this output (pin 40) is preferred on this board.
